// <auto-generated />
namespace WebServicesFigaro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddImagen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddImagen));
        
        string IMigrationMetadata.Id
        {
            get { return "201608231215009_AddImagen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
